export const ASSET_OPTIONS = {
  stock: [
    { symbol: 'THYAO', name: 'Türk Hava Yolları' },
    { symbol: 'EREGL', name: 'Ereğli Demir Çelik' },
    { symbol: 'TUPRS', name: 'Tüpraş' },
    { symbol: 'ASELS', name: 'Aselsan' },
    { symbol: 'GARAN', name: 'Garanti BBVA' },
    { symbol: 'AKBNK', name: 'Akbank' },
    { symbol: 'YKBNK', name: 'Yapı Kredi Bankası' },
    { symbol: 'ISCTR', name: 'İş Bankası (C)' },
    { symbol: 'SAHOL', name: 'Sabancı Holding' },
    { symbol: 'KCHOL', name: 'Koç Holding' },
    { symbol: 'SASA', name: 'Sasa Polyester' },
    { symbol: 'HEKTS', name: 'Hektaş' },
    { symbol: 'SISE', name: 'Şişecam' },
    { symbol: 'BIMAS', name: 'BİM Mağazalar' },
    { symbol: 'ENKAI', name: 'Enka İnşaat' },
    { symbol: 'TCELL', name: 'Turkcell' },
    { symbol: 'FROTO', name: 'Ford Otosan' },
    { symbol: 'TOASO', name: 'Tofaş Oto. Fab.' },
    { symbol: 'PGSUS', name: 'Pegasus Hava Yolları' },
    { symbol: 'KRDMD', name: 'Kardemir (D)' },
    { symbol: 'PETKM', name: 'Petkim' },
    { symbol: 'ARCLK', name: 'Arçelik' },
    { symbol: 'TTKOM', name: 'Türk Telekom' },
    { symbol: 'AAL', name: 'Ata Portföy Birinci Hisse Senedi Fonu (AAL)' },
    { symbol: 'VAKBN', name: 'Vakıfbank' },
    { symbol: 'HALKB', name: 'Halkbank' },
    { symbol: 'KOZAL', name: 'Koza Altın' },
    { symbol: 'KOZAA', name: 'Koza Anadolu' },
    { symbol: 'ODAS', name: 'Odaş Elektrik' },
    { symbol: 'ZOREN', name: 'Zorlu Enerji' },
    { symbol: 'AKSEN', name: 'Aksa Enerji' },
    { symbol: 'ASTOR', name: 'Astor Enerji' },
    { symbol: 'ALFAS', name: 'Alfa Solar Enerji' },
    { symbol: 'SMRTG', name: 'Smart Güneş Tek.' },
    { symbol: 'KMPUR', name: 'Kimteks Poliüretan' },
    { symbol: 'GESAN', name: 'Girişim Elektrik' },
    { symbol: 'TSKB', name: 'TSKB' },
    { symbol: 'ALBRK', name: 'Albaraka Türk' },
    { symbol: 'ISMEN', name: 'İş Yatırım Menkul' },
    { symbol: 'OYAKC', name: 'Oyak Çimento' },
    { symbol: 'CIMSA', name: 'Çimsa' },
    { symbol: 'ENJSA', name: 'Enerjisa' },
    { symbol: 'DOAS', name: 'Doğuş Otomotiv' },
    { symbol: 'OTKAR', name: 'Otokar' },
    { symbol: 'MGROS', name: 'Migros' },
    { symbol: 'SOKM', name: 'Şok Marketler' },
    { symbol: 'TKFEN', name: 'Tekfen Holding' },
    { symbol: 'TAVHL', name: 'TAV Havalimanları' },
    { symbol: 'DOHOL', name: 'Doğan Holding' },
    { symbol: 'ALARK', name: 'Alarko Holding' },
    { symbol: 'ECILC', name: 'Eczacıbaşı İlaç' },
    { symbol: 'AEFES', name: 'Anadolu Efes' },
    { symbol: 'CCOLA', name: 'Coca Cola İçecek' },
    { symbol: 'AYDEM', name: 'Aydem Yenilenebilir' },
    { symbol: 'GWIND', name: 'Galata Wind Enerji' },
    { symbol: 'KORDS', name: 'Kordsa' },
    { symbol: 'TUKAS', name: 'Tukaş' },
    { symbol: 'MAVI', name: 'Mavi Giyim' },
    { symbol: 'VAKKO', name: 'Vakko Tekstil' },
    { symbol: 'ISGYO', name: 'İş GYO' },
    { symbol: 'EKGYO', name: 'Emlak Konut GYO' },
    { symbol: 'TRGYO', name: 'Torunlar GYO' },
    { symbol: 'AGHOL', name: 'AG Anadolu Grubu' },
    { symbol: 'BERA', name: 'Bera Holding' },
    { symbol: 'BRSAN', name: 'Borusan Boru' },
    { symbol: 'BRYAT', name: 'Borusan Yatırım' },
    { symbol: 'AKFGY', name: 'Akfen GYO' },
    { symbol: 'AYGAZ', name: 'Aygaz' },
    { symbol: 'YENAY', name: 'Yeniay' },
    { symbol: 'GUBRF', name: 'Gübre Fabrikaları' },
    { symbol: 'BJKAS', name: 'Beşiktaş Futbol Yat.' },
    { symbol: 'GSRAY', name: 'Galatasaray Sportif' },
    { symbol: 'FENER', name: 'Fenerbahçe Futbol' },
    { symbol: 'TSPOR', name: 'Trabzonspor Sportif' },
    { symbol: 'GMSTR', name: 'QNB Finans Gümüş BYF' },
    { symbol: 'GLDTR', name: 'QNB Finans Altın BYF' },
    { symbol: 'ZGOLD', name: 'Ziraat Portföy Altın BYF' },
    { symbol: 'ALTINS1', name: 'Darphane Altın Sertifikası (ALTIN.S1)' }
  ],
  crypto: [
    { symbol: 'BTC', name: 'Bitcoin' },
    { symbol: 'ETH', name: 'Ethereum' },
    { symbol: 'USDT', name: 'Tether' },
    { symbol: 'BNB', name: 'BNB' },
    { symbol: 'SOL', name: 'Solana' },
    { symbol: 'XRP', name: 'Ripple' },
    { symbol: 'ADA', name: 'Cardano' },
    { symbol: 'AVAX', name: 'Avalanche' },
    { symbol: 'DOGE', name: 'Dogecoin' },
    { symbol: 'LINK', name: 'Chainlink' },
    { symbol: 'MATIC', name: 'Polygon' }
  ],
  commodity: [
    { symbol: 'GAU', name: 'Gram Altın' },
    { symbol: 'XAU', name: 'ONS Altın' },
    { symbol: 'XAG', name: 'Gümüş' },
    { symbol: 'BRENT', name: 'Brent Petrol' },
    { symbol: 'PLAT', name: 'Platin' },
    { symbol: 'PALL', name: 'Paladyum' }
  ],
  currency: [
    { symbol: 'USD', name: 'Amerikan Doları' },
    { symbol: 'EUR', name: 'Euro' },
    { symbol: 'GBP', name: 'İngiliz Sterlini' },
    { symbol: 'CHF', name: 'İsviçre Frangı' },
    { symbol: 'JPY', name: 'Japon Yeni' },
    { symbol: 'CAD', name: 'Kanada Doları' },
    { symbol: 'AUD', name: 'Avustralya Doları' },
    { symbol: 'SAR', name: 'Suudi Arabistan Riyali' }
  ]
};
