@echo off
mkdir stitch_assets\html
mkdir stitch_assets\screenshots

echo Downloading Finansal Kokpit (Dashboard)...
curl.exe -s -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sX2QxNDIxMzQwMjllMjQxM2E4YjYxZDVmM2Y0ZjMyNmFmEgsSBxDCxpjSkQgYAZIBJAoKcHJvamVjdF9pZBIWQhQxMDY0MTI5NTEyNTY1ODQ0ODAyNw&filename=&opi=89354086" -o stitch_assets\html\2_dashboard.html
curl.exe -s -L "https://lh3.googleusercontent.com/aida/ADBb0uhWFsVLzoBmGtPn52f8VibxyvS-1IVcFrQHfcc-7TuiNGAyYjPFim-ZzETDhy8R3OnnsDu5mkZtcdz-Z7YD4jQIdbhojN4VDzl-b9odmRDsq3VaCsb7IhqzttaATu52-YOZqmdpao5sCTjz4ND8avFMV8XJ1STnB5_yghIW7gYmp1Zg8R9fMUeIP8E2nm_9noUeoUlYi65NatF6cqCEkDjaWZpTqWpPoilRBBBDTF0a2gqwH_uPLgVUP03g" -o stitch_assets\screenshots\2_dashboard.png

echo Downloading Islemler (Transactions)...
curl.exe -s -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzgyOTExOGMyNTJkNzQyZGFhZjQ2MjM2NjZmZTc5NTExEgsSBxDCxpjSkQgYAZIBJAoKcHJvamVjdF9pZBIWQhQxMDY0MTI5NTEyNTY1ODQ0ODAyNw&filename=&opi=89354086" -o stitch_assets\html\3_transactions.html
curl.exe -s -L "https://lh3.googleusercontent.com/aida/ADBb0uirZZsURsw7SYUqCBxHZUZN5rUqYUwE9nTuWeErv0aCLwtbcfAyfgMEceF05lt3axA_yyXEvgyw_2cnN1DopSIinsqidPGR8qPl-g5qfwTkR5HJoCi8GS2fMhtQTynGiEtGq5sXTPZvcpLpQAf7vJm-e-6cTs-E6rY4hOm1RGhYCwXMBFvlCKeUtJdlpw13Kuc8VCJ2y2kWaNmXa3ewfKF_v7VwNfU6Qe2d3u3-9r1uRT-kSr7XAYCBO-tU" -o stitch_assets\screenshots\3_transactions.png

echo Downloading Yatirimlar (Investments)...
curl.exe -s -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzg3ZDNhNDM4ZTA2ZTRjN2ViMzhjZjlhZDNiODA2ODBiEgsSBxDCxpjSkQgYAZIBJAoKcHJvamVjdF9pZBIWQhQxMDY0MTI5NTEyNTY1ODQ0ODAyNw&filename=&opi=89354086" -o stitch_assets\html\4_investments.html
curl.exe -s -L "https://lh3.googleusercontent.com/aida/ADBb0ujnJGfGs59-68hg8k0NxK5rvjeqjIq3DaJRRq3R9BhLnOQIAPUg4k5s2P1bSKzl-htzAvqblK-r8li_ylfT2Mz9NwDBU10fr1KyxWczpJ9tGLZGI7RqyYVtAtBDjQzj_IgAN8BpCpzP59z6-wAdMfx70OIWD0yyTtzQn5QxlKHXQZUZOGLHUMa9y_FaFCMv-dNgiiKxgAXhokSOXcQcf6OidiZeb9ipv_Y47qjz6-uxwKhtIttctrsacFpJ" -o stitch_assets\screenshots\4_investments.png

echo Downloading Hedefler (Goals)...
curl.exe -s -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzJmODM4YmM3YjFhNTRkOTdhMzQ4Y2YxN2IzNDEyMTVkEgsSBxDCxpjSkQgYAZIBJAoKcHJvamVjdF9pZBIWQhQxMDY0MTI5NTEyNTY1ODQ0ODAyNw&filename=&opi=89354086" -o stitch_assets\html\5_goals.html
curl.exe -s -L "https://lh3.googleusercontent.com/aida/ADBb0uj1p56Wvj_coU4Oco1Hl75kF81-MCwRWN8-erXclNR0AZ1Dk7uYxppc_fFyekA_RuANAOeAqyWeS9tx0J15l8LP9DNNmYPRiCeTwnR8XsfKYLexkUxbHR6vqoCS8S30hi4lLo_2mh8bszcQPasVU76L3pV3QQxYM2nBYTCFwbGvI5kNtyc05a-TOGtO9uzj-y2MYR3pZgT3DsV06rzZKzEpV5SVvBCcknUkvT8T7c11DYyAP67qcq2xSim8" -o stitch_assets\screenshots\5_goals.png

echo Downloading Butceler (Budgets)...
curl.exe -s -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sX2MzNjVlMDhhMmY1ODQ1ZTg4MDQwY2NjNmFiNWM4MmQ3EgsSBxDCxpjSkQgYAZIBJAoKcHJvamVjdF9pZBIWQhQxMDY0MTI5NTEyNTY1ODQ0ODAyNw&filename=&opi=89354086" -o stitch_assets\html\6_budgets.html
curl.exe -s -L "https://lh3.googleusercontent.com/aida/ADBb0uiO2QPuzREBtKcmnS2UKtfYQYIvVnuj_G8po0N5pVnSOA1gMG6I7xrbdn3vXlNXmadECHqU2F_66qmgib4Z6Wfds6KqVFTRWNI2NjC8cYiasoLD6_bjNVK_GgOtMcrmMlxFd83EbaoTDFVbTlqWNr4725-5d1IdjmpucU0q_lEgGa0PLwSRFDDfURsBoNJu1iNzZU1iHXk6zPvg0guW_UBuBKXx6o-Rw5no-4v86ALfhBm79-SUFQwc26aC" -o stitch_assets\screenshots\6_budgets.png

echo Downloading Net Varlik (Net Worth)...
curl.exe -s -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzNkNDYzMmY1ZjkxYjRlYWJhODAxZGYzYjI5MjNiOGE0EgsSBxDCxpjSkQgYAZIBJAoKcHJvamVjdF9pZBIWQhQxMDY0MTI5NTEyNTY1ODQ0ODAyNw&filename=&opi=89354086" -o stitch_assets\html\7_net_worth.html
curl.exe -s -L "https://lh3.googleusercontent.com/aida/ADBb0uhIDfoCFswB_Elqhyu74Vg4vHeCYHoOMHa5_N6lYLhkBx0P94cCNHc9nWozq8a2MoEix_7M3WUohqgzsqCtnksmQq67bSwhB-qza80B-UtRaEunbVEo_lC9F_Lt03mDDVGQuZ7d3rIYRDJ1cs6CHuV4ymDvZLYcC35IWDTvPmqBAXLz0d8OSolA3skJON_3A5e2L3AhHnHi7V0IFKQVVsZ44XNAsSDz1oUBNrWR-zHN5zTjN1FwlU3Uc6nk" -o stitch_assets\screenshots\7_net_worth.png

echo Downloading Islem Detaylari (Transaction Details)...
curl.exe -s -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzVjZGFmNWI5ZjQyZjRlNTI5ZmZjZWQxNzA2Y2I3MDNhEgsSBxDCxpjSkQgYAZIBJAoKcHJvamVjdF9pZBIWQhQxMDY0MTI5NTEyNTY1ODQ0ODAyNw&filename=&opi=89354086" -o stitch_assets\html\8_transaction_details.html
curl.exe -s -L "https://lh3.googleusercontent.com/aida/ADBb0ugjH2Zov-gqJ1sKJDzvKzITZ-aow1Oxq4Cyww9eXb2daLZfR7NtSzV2WNDF8tSwDNZEik89w1ldLClVl70hmaNWCpEWTT2wIUZguE04TLX7LTt58mG5Y8l4idOKqlG6T2FbbXuqwUqClsSjq7nTdD7Zd9MNvlXIgPxdTIT5OFCD7ILaRKfO9etPOb74rNBgWwvYVKNPNmwiwLrk5nwZlIPgdXaBmHe0yWVLnQDvfXANJciClVZJL4CT8i1Z" -o stitch_assets\screenshots\8_transaction_details.png

echo Downloading Yatirim Ekleme (Add Investment)...
curl.exe -s -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzM2NDkxYzhhZDA2MDRmZTk4N2Q3NzQ1ODdlMzViODk2EgsSBxDCxpjSkQgYAZIBJAoKcHJvamVjdF9pZBIWQhQxMDY0MTI5NTEyNTY1ODQ0ODAyNw&filename=&opi=89354086" -o stitch_assets\html\9_add_investment.html
curl.exe -s -L "https://lh3.googleusercontent.com/aida/ADBb0uhjwOg5PhXj1ZjdJrnJdoPRN-h0HBRuFrXKeinv3n-dbpKaRYcwc4Vwio8HXazk2Y4LRS_G1QQfV4tUabMQMa3pzAiEHrqEA6b-1jsaCw6lZ05zdguU6_FWEc7cLKFPgErJImlnljVSg6ZMpBvaQiIcujtNf3rswBqsa2tAEIyLJeWdTlB8ze5dFxmqjAQTVAZ3o1NXoBjbJNuZlXDpu5oUzI1lwnDHY-cNQ4b6JMPGgcfN1HNN4_fBaYA" -o stitch_assets\screenshots\9_add_investment.png

echo Downloading AI Finansal Rapor (AI Report)...
curl.exe -s -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzc0ZjljNWY0MmIyYzQ0NDRhYzg3ZTc0YzBlMTMxZjc0EgsSBxDCxpjSkQgYAZIBJAoKcHJvamVjdF9pZBIWQhQxMDY0MTI5NTEyNTY1ODQ0ODAyNw&filename=&opi=89354086" -o stitch_assets\html\10_ai_report.html
curl.exe -s -L "https://lh3.googleusercontent.com/aida/ADBb0uieF0Hk9QmLxoXStgT8vPh1JnPIDf9SIVd9B8Bvzfom-hgGOk2Zm6ClO44tQjL2EdaJnSHG9N9B7GQFTLYFyxGtqxenRRLqn7TbfW9tsx79105MGnm8xO02xOoTq6OoGS2czQSr7Hfq6zC8eAvhD8NCqjhj-CLUjmZ3a0mYSzKNIXsXVSy7R_Br7peBIzWyzfQjN9jSmQfA2z6rsY6CZz7fMqWuJ608zYkI4O8itrasdalprQlaZmOwlKMS" -o stitch_assets\screenshots\10_ai_report.png

echo Downloading Profil ve Ayarlar (Profile Settings)...
curl.exe -s -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sX2FiYzRjNmIzYTc1ZTQ1YzBhYjRkZWJiMjBlOTY3NTRmEgsSBxDCxpjSkQgYAZIBJAoKcHJvamVjdF9pZBIWQhQxMDY0MTI5NTEyNTY1ODQ0ODAyNw&filename=&opi=89354086" -o stitch_assets\html\11_profile_settings.html
curl.exe -s -L "https://lh3.googleusercontent.com/aida/ADBb0uiFD4BOHGC4XN8SDvTBBxubFyDqP17PrmBcA-Asg3iUhr0Xzu62tZBhWeKh_4Jd5u6eTcIAayTTAEZNPAV3fNvu_yzJPtfVjrnGhPXwb4Isylfaca0GZWO_cwmtRGv4oF2W4ZLM_ltcLW9_s0jfyH9XyyhMjcPiIdMH4vXC893FNoqYxqnQsM-MnQX-z19SJx1GNuV80KdKVFg5re2PoqmcZDpOHx48PAOkjaZeDGf0G1eM-5dDCUtzZXB5" -o stitch_assets\screenshots\11_profile_settings.png

echo Download complete.
